import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Nav } from '@/components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale = 1.0, 
      maximum-scale=1.0, user-scalable=no" />
      <body style={{margin:"0px", overflowX:"hidden"}}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
